<?php
//#section#[header]
// Namespace
namespace UI\Developer;

// Use Important Headers
use \API\Platform\importer;
use \Exception;

// Check Platform Existance
if (!defined('_RB_PLATFORM_'))
	throw new Exception("Platform is not defined!");
//#section_end#
//#section#[class]
/**
 * @library	UI
 * @package	Developer
 * @namespace	\
 * 
 * @copyright	Copyright (C) 2014 Skyworks SD. All rights reserved.
 */

importer::import("DEV", "Profiler", "ui::logViewer");

use \DEV\Profiler\ui\logViewer;

/**
 * Visual Log Controller
 * 
 * Shows a visual representation of the log messages generated by the system.
 * 
 * @version	1.0-2
 * @created	December 19, 2013, 16:41 (EET)
 * @revised	September 8, 2014, 16:37 (EEST)
 * 
 * @deprecated	Use \DEV\Profiler\logViewer instead.
 */
class logController extends logViewer {}
//#section_end#
?>