<?php
//#section#[header]
// Namespace
namespace DEV\Websites\source;

// Use Important Headers
use \API\Platform\importer;
use \Exception;

// Check Platform Existance
if (!defined('_RB_PLATFORM_'))
	throw new Exception("Platform is not defined!");
//#section_end#
//#section#[class]
/**
 * @library	DEV
 * @package	Apps
 * @namespace	\source
 * 
 * @copyright	Copyright (C) 2014 Skyworks SD. All rights reserved.
 */

importer::import("API", "Resources", "filesystem::fileManager");
importer::import("DEV", "Prototype", "classObject");
importer::import("DEV", "Prototype", "sourceMap");
importer::import("DEV", "Websites", "website");
importer::import("DEV", "Websites", "source::srcPackage");
importer::import("DEV", "Tools", "parsers::phpParser");
importer::import("DEV", "Tools", "coders::phpCoder");
importer::import("DEV", "Version", "vcs");
importer::import("DEV", "Resources", "paths");

use \API\Resources\filesystem\fileManager;
use \DEV\Prototype\classObject;
use \DEV\Prototype\sourceMap;
use \DEV\Websites\website;
use \DEV\Websites\source\srcPackage;
use \DEV\Tools\parsers\phpParser;
use \DEV\Tools\coders\phpCoder;
use \DEV\Version\vcs;
use \DEV\Resources\paths;

/**
 * Application Source Object
 * 
 * {description}
 * 
 * @version	1.0-3
 * @created	August 22, 2014, 12:29 (EEST)
 * @revised	September 11, 2014, 20:18 (EEST)
 */
class srcObject extends classObject
{
	/**
	 * The application object.
	 * 
	 * @type	application
	 */
	private $app;
	
	/**
	 * The sourceMap object.
	 * 
	 * @type	sourceMap
	 */
	private $sourceMap;
	
	/**
	 * The source vcs manager object.
	 * 
	 * @type	vcs
	 */
	private $vcs;
	
	/**
	 * Initializes the vcs information for the object and constructs the classObject.
	 * 
	 * @param	integer	$appID
	 * 		The application id.
	 * 
	 * @param	string	$package
	 * 		The object's package.
	 * 
	 * @param	string	$namespace
	 * 		The object's namespace (separated by "::" or "_").
	 * 
	 * @param	string	$objectName
	 * 		The object's name.
	 * 
	 * @return	void
	 */
	public function __construct($appID, $package, $namespace = "", $objectName = NULL)
	{
		// Init application
		$this->app = new application($appID);
		$this->vcs = new vcs($appID);
		
		// Load source map
		$this->loadSourceMap();
		
		// Parent construct
		$namespace = str_replace("_", "::", $namespace);
		parent::__construct(srcPackage::LIB_NAME, $package, $namespace, $objectName);
	}
	
	/**
	 * Implementation of the abstract function from the parent class.
	 * Returns the full path of the object inside the repository.
	 * 
	 * @return	string
	 * 		The object's full path.
	 */
	protected function getObjectFullPath()
	{
		$itemID = $this->getItemID();
		return $this->vcs->getItemTrunkPath($itemID);
	}
	
	/**
	 * Create a new application source object.
	 * 
	 * @param	string	$name
	 * 		The object's name.
	 * 
	 * @param	string	$title
	 * 		The object's title.
	 * 
	 * @return	boolean
	 * 		True on success, false on failure.
	 */
	public function create($name, $title)
	{
		// Set vars
		$this->name = $name;
		$this->title = ($title == "" ? $name : $title);
		
		// Create index
		$proceed = $this->sourceMap->createObject($this->library, $this->package, $this->namespace, $this->name, $this->title);
		if (!$proceed)
			return FALSE;
		
		// Update map file vcs item
		$this->updateMapFile();
		
		// Create vcs item
		$itemID = $this->getItemID();
		$itemPath = application::SOURCE_FOLDER."/".$this->getItemPath();
		$itemName = $this->getItemFullname();
		$itemTrunkPath = $this->vcs->createItem($itemID, $itemPath, $itemName, $isFolder = TRUE);
		
		// Create classObject
		parent::create($name);
		
		// Init files
		$this->updateSourceCode();
		$this->updateSourceDoc();
		
		return TRUE;
	}
	
	/**
	 * Gets the id of the current vcs item.
	 * 
	 * @return	string
	 * 		The item's id.
	 */
	protected function getItemID()
	{
		$suffix = "cl"."_".$this->library."_".$this->package."_".$this->namespace."_".$this->name;
		return $this->app->getItemID($suffix);
	}
	
	/**
	 * Updates the source code of the object.
	 * 
	 * @param	string	$code
	 * 		The new source code.
	 * 
	 * @return	mixed
	 * 		Returns TRUE on success or FALSE on failure.
	 * 		Returns a string telling whether there is a syntax error in the php file.
	 */
	public function updateSourceCode($code = "")
	{
		// Update vcs item
		$this->updateItem();
		
		// Get SDK Object Class Header
		$header = $this->buildHeader();
		
		// Update Source Code
		return parent::updateSourceCode($header, $code);
	}
	
	
	/**
	 * Updates the source documentation of the object.
	 * 
	 * @param	string	$content
	 * 		The documentation in xml format.
	 * 		The documentation should be generated by the classDocumentor.
	 * 
	 * @return	boolean
	 * 		True on success, false on failure.
	 */
	public function updateSourceDoc($content = "")
	{
		// Update vcs item
		$this->updateItem();
		return parent::updateSourceDoc($content);
	}
	
	/**
	 * Updates the javascript code of the object.
	 * 
	 * @param	string	$code
	 * 		The new javascript code.
	 * 
	 * @return	boolean
	 * 		True on success, false on failure.
	 */
	public function updateJSCode($code = "")
	{
		// Update vcs item
		$this->updateItem();
		return parent::updateJSCode($code);
	}
	
	/**
	 * Updates the css code of the object.
	 * 
	 * @param	string	$code
	 * 		The new css code.
	 * 
	 * @return	boolean
	 * 		True on success, false on failure.
	 */
	public function updateCSSCode($code = "")
	{
		// Update vcs item
		$this->updateItem();
		return parent::updateCSSCode($code);
	}
	
	/**
	 * Updates the css model of the object.
	 * 
	 * @param	string	$model
	 * 		The new css model in html format.
	 * 
	 * @return	boolean
	 * 		True on success, false on failure.
	 */
	public function updateCSSModel($model = "")
	{
		// Update vcs item
		$this->updateItem();
		return parent::updateCSSModel($model);
	}
	
	/**
	 * Build the source's header and returns it.
	 * 
	 * @return	string
	 * 		The object's header code.
	 */
	private function buildHeader()
	{  
		$path = systemRoot.paths::getDevRsrcPath()."/headers/application/sourceObject.inc";
		$header = fileManager::get($path);
		return phpParser::unwrap($header);
	}
	
	/**
	 * Runs (includes) the trunk's source code file.
	 * 
	 * @return	mixed
	 * 		The include result of the object.
	 * 		Normally is void.
	 * 
	 * @deprecated	Use loadFromTrunk() instead.
	 */
	public function loadSourceCode()
	{
		return $this->loadFromTrunk();
	}
	
	/**
	 * Runs (includes) the trunk's source code file.
	 * 
	 * @return	mixed
	 * 		The include result of the object.
	 * 		Normally is void.
	 */
	public function loadFromTrunk()
	{
		return parent::includeSourceCode();
	}
	
	/**
	 * Runs (includes) the working branch's source code file.
	 * 
	 * @return	mixed
	 * 		The include result of the object.
	 * 		Normally is void.
	 */
	public function loadFromWBranch()
	{
		$itemID = $this->getItemID();
		$itemFolder = $this->vcs->getItemBranchPath($itemID);
		
		return importer::incl($itemFolder.parent::SOURCE_FOLDER."/class.php", FALSE, TRUE);
	}
	
	/**
	 * Update the item in the working index of the vcs.
	 * 
	 * @param	boolean	$forceCommit
	 * 		Tells whether the object will be included in the next commit.
	 * 
	 * @return	void
	 */
	public function updateItem($forceCommit = FALSE)
	{
		// Get item ID
		$itemID = $this->getItemID();

		// Update item working index
		$this->vcs->updateItem($itemID, $forceCommit);
	}
	
	/**
	 * Removes the object from the SDK.
	 * 
	 * @return	boolean
	 * 		True on success and false on failure.
	 */
	public function remove()
	{
		// Delete from source map index
		$status = FALSE;
		try
		{
			$objectName = (empty($this->namespace) ? "" : $this->namespace."::").$this->name;
			$status = $this->sourceMap->deleteObject($this->library, $this->package, $objectName);
		}
		catch (Exception $ex)
		{
			$status = $ex->getMessage();
		}
		
		// If delete is successful, update map file and delete from vcs
		if ($status === TRUE)
		{
			// Update vcs map file
			$this->updateMapFile();
			
			// Remove object from vcs
			$itemID = $this->getItemID();
			$this->vcs->deleteItem($itemID);
		}
		
		return $status;
	}
	
	/**
	 * Gets the item's path (with library, package, namespace etc) for the vcs.
	 * 
	 * @return	string
	 * 		The item's path.
	 */
	private function getItemPath()
	{
		$namespace = str_replace("::", "/", $this->namespace);
		return "/".$this->library."/".$this->package."/".$namespace."/";
	}
	
	/**
	 * Initializes the source map object for getting the source information from the source index.
	 * 
	 * @return	object
	 * 		The sourceMap object.
	 */
	private function loadSourceMap()
	{
		if (empty($this->sourceMap))
		{
			// Get source index file path
			$itemID = $this->app->getItemID("sourceIndex");
			$mapFilePath = $this->vcs->getItemTrunkPath($itemID);
			$this->sourceMap = new sourceMap(dirname($mapFilePath), basename($mapFilePath));
		}
		
		return $this->sourceMap;
	}
	
	/**
	 * Updates the source map index file in the vcs.
	 * 
	 * @return	void
	 */
	private function updateMapFile()
	{
		// Get source index file path
		$itemID = $this->app->getItemID("sourceIndex");
		$this->vcs->updateItem($itemID, TRUE);
	}
}
//#section_end#
?>