<?php
//#section#[header]
// Namespace
namespace ESS\Prototype\html;

// Use Important Headers
use \API\Platform\importer;
use \Exception;

// Check Platform Existance
if (!defined('_RB_PLATFORM_')) throw new Exception("Platform is not defined!");
//#section_end#
//#section#[class]
/**
 * @library	ESS
 * @package	Prototype
 * @namespace	\html
 * 
 * @copyright	Copyright (C) 2013 Skyworks SD. All rights reserved.
 */

importer::import("ESS", "Protocol", "client::NavigatorProtocol");
importer::import("ESS", "Prototype", "UIObjectPrototype");
importer::import("UI", "Html", "DOM");

use \ESS\Protocol\client\NavigatorProtocol;
use \ESS\Prototype\UIObjectPrototype;
use \UI\Html\DOM;

/**
 * Menu Prototype
 * 
 * This is the menu prototype (implements the composite pattern).
 * All menus (and extensions of it) must inherit this prototype and build a proper menu object.
 * 
 * @version	{empty}
 * @created	March 7, 2013, 12:04 (EET)
 * @revised	April 26, 2013, 14:51 (EEST)
 */
class MenuPrototype extends UIObjectPrototype
{
	/**
	 * The menulist of this menu.
	 * 
	 * @type	DOMElement
	 */
	protected $menuList;
	
	/**
	 * Builds the spine of the menu and sets the UIObject.
	 * 
	 * @param	string	$id
	 * 		The menu id
	 * 
	 * @param	string	$class
	 * 		The menu class (for styling reasons)
	 * 
	 * @return	MenuPrototype
	 */
	public function build($id = "", $class = "")
	{
		// Build Menu Container
		$menuContainer = DOM::create("div", "", $id, $class);
		$this->set($menuContainer);
		
		// Build Menu List
		$this->menuList = DOM::create("ul");
		DOM::append($menuContainer, $this->menuList);
		
		return $this;
	}
	
	/**
	 * Creates a menuItem.
	 * 
	 * @param	string	$id
	 * 		The id of the menuItem (if any)
	 * 
	 * @param	string	$class
	 * 		The class of the menuItem (if any)
	 * 
	 * @param	DOMElement	$context
	 * 		The context of the menuItem (if any)
	 * 
	 * @return	DOMElement
	 */
	public function getMenuItem($id = "", $class = "", $context = NULL)
	{
		$item = DOM::create("li", "", $id, $class);
		
		if (!is_null($context))
			DOM::append($item, $context);
			
		return $item;
	}
	
	/**
	 * Creates a menuItem and appends it to the menuList.
	 * 
	 * @param	string	$id
	 * 		The id of the menuItem (if any)
	 * 
	 * @param	string	$class
	 * 		The class of the menuItem (if any)
	 * 
	 * @param	DOMElement	$context
	 * 		The context of the menuItem (if any)
	 * 
	 * @return	DOMElement
	 */
	public function createMenuItem($id = "", $class = "", $context = NULL)
	{
		$item = $this->getMenuItem($id, $class, $context);
		
		// Append the item to the parent
		DOM::append($this->menuList, $item);
		
		return $item;
	}
	
	/**
	 * Insert a ready menu item generated by getMenuItem() or a product.
	 * 
	 * @param	DOMElement	$item
	 * 		The menu item to be inserted.
	 * 
	 * @return	MenuPrototype
	 */
	public function insertMenuItem($item)
	{
		if (!is_null($item))
			DOM::append($this->menuList, $item);
		
		return $this;
	}
	
	public function getNavProtocol()
	{
		return new NavigatorProtocol();
	}
	
	/**
	 * Adds static navigation handler
	 * 
	 * @param	DOMElement	$element
	 * 		The element to receive the navigation handler
	 * 
	 * @param	string	$ref
	 * 		The target's id to perform the action
	 * 
	 * @param	string	$targetcontainer
	 * 		The container's class of the group in which the target resides
	 * 
	 * @param	string	$targetgroup
	 * 		The group of the items to handle together when performing the action to the target. For more information, see the NavigatorProtocol.
	 * 
	 * @param	string	$navgroup
	 * 		The group of navigation items, among which the handler element will be selected
	 * 
	 * @param	string	$display
	 * 		Defines the type of action for the rest items of the group. For more information, see the NavigatorProtocol.
	 * 
	 * @return	void
	 */
	public static function addNavigation($element, $ref, $targetcontainer, $targetgroup, $navgroup, $display = "none")
	{
		NavigatorProtocol::staticNav($element, $ref, $targetcontainer, $targetgroup, $navgroup, $display);
	}
	
	/**
	 * Adds a navigation group selector to the given element.
	 * 
	 * @param	DOMElement	$element
	 * 		The group selector element.
	 * 
	 * @param	string	$selector
	 * 		The selector.
	 * 
	 * @return	void
	 */
	public static function addNavigationSelector($element, $selector)
	{
		NavigatorProtocol::selector($element, $selector);
	}
	
	/**
	 * Creates a static navigation group.
	 * For more information, see the NavigatorProtocol.
	 * 
	 * @param	string	$id
	 * 		The id of the navigation group.
	 * 
	 * @param	string	$groupSelector
	 * 		The static navigation selector for the group.
	 * 
	 * @return	DOMElement
	 */
	public static function getNavigationGroup($id, $groupSelector)
	{
		// Create Navigation Group
		$navGroup = DOM::create("div", "", $id);
		NavigatorProtocol::selector($navGroup, $groupSelector);
		
		return $navGroup;
	}
}
//#section_end#
?>